<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer</name>
   <tag></tag>
   <elementGuidId>f7a5c69c-f29e-4c1d-a197-7ded547910db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;customer\.php&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'customer.php']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Customer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bea903b3-739e-485c-9d99-d41d400d327f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>customer.php</value>
      <webElementGuid>ec15c2c1-92a9-476c-b6e0-220184aeb09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			             Customer
			          </value>
      <webElementGuid>56025af0-50c6-4675-8dc1-1393459a0f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-422b1c55db99ca638603e0bfe1ea0439</value>
      <webElementGuid>3f67c7bd-aaa9-42f1-a0e2-6d5be11e32c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'customer.php']</value>
      <webElementGuid>009c35b6-ab8a-4dad-8c90-5e2a5c77c7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'customer.php']</value>
      <webElementGuid>286480c2-7403-4ea3-83aa-bdefdb923c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'customer.php' and (text() = '
			             Customer
			          ' or . = '
			             Customer
			          ')]</value>
      <webElementGuid>a0eee661-8cce-4492-868f-fdd08ad33947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
