<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cust_password</name>
   <tag></tag>
   <elementGuidId>64bdb3ff-2948-4f5c-a95d-3e3093bcdbfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'cust_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;cust_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;cust_password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8eafedb-80a6-428b-a561-663f2412a642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2aa2d9ac-e37b-4e24-bc21-753b70207363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d8ce0a5-0424-4e05-9af6-4a5e8aebaae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cust_password</value>
      <webElementGuid>5ba3a06a-c358-48f8-a41a-3c26b23155f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b9644bf75e3aebcf79d127f1bd820fb</value>
      <webElementGuid>21020629-10b2-406a-8973-326dabc3379d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'cust_password']</value>
      <webElementGuid>eeecaa9f-85c7-4cc9-a227-cc54e9d5a1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'cust_password']</value>
      <webElementGuid>0fd90993-d984-435e-967b-334dd3df7c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'cust_password']</value>
      <webElementGuid>c713ee0b-5b43-46ff-8b6f-b4a2986c19b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
