<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQ</name>
   <tag></tag>
   <elementGuidId>306c756b-c0f4-487a-9897-d82ad6fb41c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;faq\.php&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'faq.php']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; FAQ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>426f924f-b16a-47d9-a974-62db25bb9eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>faq.php</value>
      <webElementGuid>059e0776-f29d-48b4-9771-851016e0f268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			             FAQ
			          </value>
      <webElementGuid>958bf9e0-e6d9-46b1-8f6f-fd67933dbef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-94ca292e025e9a2951778ed2cb8ce096</value>
      <webElementGuid>07bc420d-1ef7-4a34-ab68-811848122947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'faq.php']</value>
      <webElementGuid>05aae5e3-3b3c-481c-8c6d-b2253395c4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'faq.php']</value>
      <webElementGuid>98acec65-dd16-4546-b06c-14f5e0d064ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'faq.php' and (text() = '
			             FAQ
			          ' or . = '
			             FAQ
			          ')]</value>
      <webElementGuid>3d89807c-caf4-4c7c-a178-9d0baf930bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
