<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form1</name>
   <tag></tag>
   <elementGuidId>a02670c7-f244-40e3-bd29-7b2018ce82a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;form1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'form1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bf4d5df-276c-419b-b812-f591b2c25aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>83070d1e-0a13-4c7e-9577-55627510cc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4ce13097-22cf-4a15-aa5f-f53bb1f7fd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>25633b89-fd06-4f78-882f-afaf5ff7de1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form1</value>
      <webElementGuid>88d10775-3063-415b-a04b-b5a25242e06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-170b5e9b5df7b0a11de05346f479b39c</value>
      <webElementGuid>b665ee21-07eb-4452-a27f-7d75a5962aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'form1']</value>
      <webElementGuid>69d9789d-a194-4181-b226-9dcee256b524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'form1']</value>
      <webElementGuid>c3b4ff1e-b0f8-4f81-94a8-7240c44244cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'form1']</value>
      <webElementGuid>44f7c466-084d-478b-bf8c-a1f5662fd61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
