<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Delete Confirmation</name>
   <tag></tag>
   <elementGuidId>2830f777-2552-4dd4-82b1-431a43095ae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myModalLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='myModalLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Delete Confirmation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d84bf9af-0d72-4bdc-beba-7cfb3c9a1876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>b2018c8d-d0a2-4d1f-80e9-611279090e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myModalLabel</value>
      <webElementGuid>8ba36b57-e3c5-4c67-910a-87a7bbf21eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Confirmation</value>
      <webElementGuid>02bf00a8-fd56-4832-be93-e3cc2522fc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModalLabel&quot;)</value>
      <webElementGuid>4f2fe481-9dc8-439d-8c7d-4e64ea70cc4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='myModalLabel']</value>
      <webElementGuid>88637bde-f14e-4b25-aed7-c399f1c2193f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirm-delete']/div/div/div/h4</value>
      <webElementGuid>781cd0f2-8d65-4bea-9ded-c9f89839b7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/following::h4[1]</value>
      <webElementGuid>e3ba279d-4aa0-4a7c-a5fc-4326352ab690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::h4[1]</value>
      <webElementGuid>bfcb384d-2d1d-4686-8991-ecbcb371a334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure want to delete this item?'])[1]/preceding::h4[1]</value>
      <webElementGuid>fca6a305-da49-4d12-ba0e-4a8c130e9114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::h4[1]</value>
      <webElementGuid>a5d42edb-cd00-4d2c-9293-b64f77d667bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Confirmation']/parent::*</value>
      <webElementGuid>7e63453e-6c50-4f56-a3ae-84a08f227665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h4</value>
      <webElementGuid>e6928472-b6c5-4bc6-875b-c2aa0e99dc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'myModalLabel' and (text() = 'Delete Confirmation' or . = 'Delete Confirmation')]</value>
      <webElementGuid>9cd75c3e-27ea-4ac3-a303-a905cb8b00ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
