<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Mid Level Category</name>
   <tag></tag>
   <elementGuidId>ff4db088-52c6-4f35-80a9-fd32c9eba75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-mcat_id-cs-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-mcat_id-cs-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Select Mid Level Category&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d0eac0d-6032-4fd3-a75d-7afe1b2f9895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a6ecdcb0-aba4-4262-8da6-0b12e2e527f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-mcat_id-cs-container</value>
      <webElementGuid>97ab33db-f5c5-4fb3-b5f1-44bc24ecdf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Mid Level Category</value>
      <webElementGuid>d984d353-0adc-4c6b-9fdf-12fb476e9c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Mid Level Category</value>
      <webElementGuid>45701476-9000-41ca-bbef-439c4815adcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-mcat_id-cs-container&quot;)</value>
      <webElementGuid>7cde9b15-8323-4494-8959-5ca0e07cf267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-mcat_id-cs-container']</value>
      <webElementGuid>f0625a0b-3cb0-4e45-b117-0ca77f889fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>eb60ad5c-df90-475f-9f99-a74da40a33ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[3]</value>
      <webElementGuid>73bb3d45-cd0d-4736-808a-a837146a5169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>96dc8000-1df8-4eb8-8bec-6fe4da007807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-mcat_id-cs-container' and @title = 'Select Mid Level Category' and (text() = 'Select Mid Level Category' or . = 'Select Mid Level Category')]</value>
      <webElementGuid>da946585-ba35-43ef-96f6-60d2683287eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-mcat_id-tt-container']</value>
      <webElementGuid>099b5dbb-db3a-41fe-8ca1-c4428c5bb7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-mcat_id-tt-container' and @title = 'Select Mid Level Category' and (text() = 'Select Mid Level Category' or . = 'Select Mid Level Category')]</value>
      <webElementGuid>7508bd02-7513-4199-8b72-71240f50f511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
