<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_User Image</name>
   <tag></tag>
   <elementGuidId>94d8436a-b69c-4333-9627-825ad98a08d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.user-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' user-image ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User Image Hammad Hassan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0bb85358-222f-4ff5-b1b8-90f9a9dad009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/uploads/user-1.jpg</value>
      <webElementGuid>b5f68270-a5ba-4abc-afbe-7de77d09384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-image</value>
      <webElementGuid>56b35d79-4a51-4dad-b8bd-fae65fe6c38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Image</value>
      <webElementGuid>534d4087-4b1f-4b85-ae8e-108fef0502bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aa8cb2265840af250bea536c5b746a1f</value>
      <webElementGuid>dfbc81c9-b2ee-42bd-887a-ab1762a55c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' user-image ')]</value>
      <webElementGuid>a2df8fa4-3264-4e1d-9c9f-36ec6c9b82e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' user-image ')]</value>
      <webElementGuid>33a11b9f-c107-490d-bc50-1525f44132c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../assets/uploads/user-1.jpg' and @alt = 'User Image']</value>
      <webElementGuid>cfded2eb-b9ee-4ad3-93dd-2ef363d69734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
