<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1</name>
   <tag></tag>
   <elementGuidId>09f3767a-4837-493f-97ce-0bab0119c7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bootstrap-touch-slider']/ol/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.carousel-indicators > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bootstrap-touch-slider >> internal:role=listitem >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>05ae7506-5e04-4cd2-b687-eccc8311a548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#bootstrap-touch-slider</value>
      <webElementGuid>6c42bff8-4a21-4d4d-9ad7-92e6e727a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slide-to</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>82d7963b-f48d-44bb-8228-b6803c2202fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bootstrap-touch-slider&quot;)/ol[@class=&quot;carousel-indicators&quot;]/li[2]</value>
      <webElementGuid>5e187b49-4d6d-4add-9a74-ca5f01e49179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bootstrap-touch-slider']/ol/li[2]</value>
      <webElementGuid>3ee46a6f-b774-4dd3-9dd0-2a127ff52e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]</value>
      <webElementGuid>74ed6d6d-6d46-49f2-9901-f8aa44c0ec13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
