<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next_prod-pager-thumb_1</name>
   <tag></tag>
   <elementGuidId>73ff12b6-7e61-4a83-b252-5e4b81c10b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prod-pager']/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.prod-pager-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#prod-pager >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2932b2b4-80d3-46b8-a3db-e2861984e294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prod-pager-thumb</value>
      <webElementGuid>0d549c22-5cfb-41fd-99df-478359464cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prod-pager&quot;)/a[1]/div[@class=&quot;prod-pager-thumb&quot;]</value>
      <webElementGuid>ba2bdf18-9a91-4102-9f93-3ddcf81e0ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prod-pager']/a/div</value>
      <webElementGuid>4263c781-da24-4dbd-98ff-bc6d5ea60988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>fbbe7684-9281-42ab-b1b3-7a6c94b69e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
