<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>6d7a0308-83f4-4e13-a634-766798ad99f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(10) > a.btn.btn-danger.btn-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Delete')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2 Facial Wash Facial Wash -100 abc 12 No No Women Beauty Products Skincare Edit Delete&quot;i] >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3c74259-f97f-4fce-8579-a74f7be3a82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8594db4b-e543-48da-8479-ae5744e41d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-xs</value>
      <webElementGuid>c153ba54-9eb2-408b-a289-868e81e78988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>product-delete.php?id=96</value>
      <webElementGuid>e7c4458c-2e02-4910-8435-9a351fae7b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>91ba713a-5506-4e84-859a-34cfc061cafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#confirm-delete</value>
      <webElementGuid>682c95e7-9bdf-4913-898d-1756b09817f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5be31cef-4d76-4bc2-bd5d-fc4a538e5fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[10]/a[@class=&quot;btn btn-danger btn-xs&quot;]</value>
      <webElementGuid>bec3fac5-b752-408d-b546-63e8fd615e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[2]/td[10]/a[2]</value>
      <webElementGuid>9fdab178-6e31-4bea-85e3-d500acb1afb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[2]</value>
      <webElementGuid>5da10d01-da84-40c7-a467-d04ebc86ad8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::a[1]</value>
      <webElementGuid>e252b91e-b977-4c89-881a-8d27f8080f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WomenBeauty ProductsSkincare'])[1]/following::a[2]</value>
      <webElementGuid>09bbf5da-3398-4e3c-9a49-615ea083af1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans for Women - Denim'])[1]/preceding::a[1]</value>
      <webElementGuid>d1a349bc-9fac-47f2-b2e1-94a7bfbc83ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::a[1]</value>
      <webElementGuid>ccd218e3-a0d8-45f6-b6ad-f83bf2823b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>d76c2576-f37a-4406-a97e-32451f9dc463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/a[2]</value>
      <webElementGuid>df701b0e-e3d9-41e4-ba94-40cfb5ca4e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>f1dd138e-9ec1-4f3a-811c-31ad0cf1d5f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
