<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Subscriber</name>
   <tag></tag>
   <elementGuidId>d3dc3d67-58ab-46ae-aef3-ae15edb2ac07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;subscriber\.php&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'subscriber.php']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Subscriber&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da687e68-5755-4cad-b88a-cfdd88923d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>subscriber.php</value>
      <webElementGuid>994f3dcf-0bc6-40c7-9f42-e495e8533768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			             Subscriber
			          </value>
      <webElementGuid>2b4e002d-ad19-4389-8ad2-4d1736193bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-84078a53ca7461221f9bb5218c6e0c43</value>
      <webElementGuid>93f211ab-8706-4f33-b7c1-db2fa8ed0863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'subscriber.php']</value>
      <webElementGuid>b7349e96-b014-42ad-975b-14e8c0485247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'subscriber.php']</value>
      <webElementGuid>da1761ac-fb55-44a7-be4c-4b8ec6fdfe11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'subscriber.php' and (text() = '
			             Subscriber
			          ' or . = '
			             Subscriber
			          ')]</value>
      <webElementGuid>c239f71e-162e-487b-96c8-b4f58d07edb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
