<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_note-icon-magic</name>
   <tag></tag>
   <elementGuidId>c20527e8-55cc-406c-bf41-a8a3dee487e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.note-icon-magic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-magic ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9d23df88-747c-4d4d-bf6d-c32c86e8330c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-icon-magic</value>
      <webElementGuid>1b9db80a-1578-42db-b46d-dff992eef8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-835f7b56b21e631ece3242dae3699fc6</value>
      <webElementGuid>4d303a27-a3f8-42be-bb01-5ad7448fe0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-magic ')]</value>
      <webElementGuid>2ec5325b-ee88-48cd-8e93-1e81d536688f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-magic ')]</value>
      <webElementGuid>cb5aa15e-a71b-43be-a1a3-f43883136679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
