<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_note-icon-underline</name>
   <tag></tag>
   <elementGuidId>bb3e5355-8f75-4aa7-9b38-34347a2cbe69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.note-icon-underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>02983c71-fd5c-4a9d-bffc-837f2d86fd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-icon-underline</value>
      <webElementGuid>11b4424c-0bb2-4212-94c7-c72d8824ed5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-781d68e9066a659907d10753d6028932</value>
      <webElementGuid>dc37bd4e-1361-4c50-aa64-feda67cb6df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      <webElementGuid>542e60b8-87fc-4ff3-a677-72e29040ac4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      <webElementGuid>48a195fb-a45c-4fbd-869c-5799684b14c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
