<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_note-icon-underline</name>
   <tag></tag>
   <elementGuidId>c8dac60d-bcbf-4921-84d3-58659d16bf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.note-icon-underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>725c7301-e029-40b5-bbf8-af5917c968fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-icon-underline</value>
      <webElementGuid>4a9f0567-1f67-4149-b166-6e4285baaefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-781d68e9066a659907d10753d6028932</value>
      <webElementGuid>3f268047-991c-4eb2-8555-3e0737681874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      <webElementGuid>84e03cca-1f02-4974-91e8-314e25af1d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' note-icon-underline ')]</value>
      <webElementGuid>9266048f-2ee0-4a5a-a043-ab53bfc454c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
