<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address</name>
   <tag></tag>
   <elementGuidId>88d6ebf0-288a-4e0c-b815-68e308efe149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce2bef1c-0b0f-4866-abbb-6437a6ca172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92b0d396-dde5-4616-904e-27f4fc810076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>5a0f84af-5032-43d0-82f0-dfccd93bf3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8a969f05-5819-4d55-abfe-5c16457dac89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0eb685b0-0601-4605-9e55-68f7db5f7960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9d9b542d-ecfa-4e52-bc5a-3d5aaa415368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ff323be03ffe3004334bd041dab0422</value>
      <webElementGuid>5683861a-16f6-4f77-8c1e-de7da6ba0958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'email']</value>
      <webElementGuid>c63bf5fb-1bf6-4d47-9ad3-f8dd39a08bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'email']</value>
      <webElementGuid>75bdcb53-7439-456e-a42b-2206511654db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email address' and @name = 'email' and @type = 'email']</value>
      <webElementGuid>96952166-e860-4faa-9718-ac2474dd3e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
