<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_indriani</name>
   <tag></tag>
   <elementGuidId>81ef9087-e762-44dd-bd42-e7395136cb1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.odd:nth-child(3) td:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 3)]//*[(name() = 'td') and (position() = 2)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;indriani&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53a6d45e-2bd0-4f12-8c64-4464a9ea1afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>indriani</value>
      <webElementGuid>fd9898ec-dae6-45b7-a6d9-4da5786cec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5e77da22b9d7d4cd2fb14cfa83aab109</value>
      <webElementGuid>3ca919a4-7570-4fcd-a5a4-04180eb89b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 3)]//*[(name() = 'td') and (position() = 2)]</value>
      <webElementGuid>e2d5f821-cc99-49d0-829a-1b0cf915bc87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 3)]//*[(name() = 'td') and (position() = 2)]</value>
      <webElementGuid>b6757188-6fff-4c88-aac3-f72e4870fd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'indriani' or . = 'indriani')]</value>
      <webElementGuid>dad723dd-cd43-4659-be16-392be8002c5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
