<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Page</name>
   <tag></tag>
   <elementGuidId>fa4c9d41-d171-4a3d-9923-a06fa4dce57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'page.php']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;page\.php&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Page&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06971fd2-f746-4d37-90b8-99ddf63fdb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>page.php</value>
      <webElementGuid>cad4e634-ce44-4e85-b456-d41fcf23c2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			             Page
			          </value>
      <webElementGuid>5998d585-3e17-4495-956e-3b227325e5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d325a63e2139c02e821673a5c65ca272</value>
      <webElementGuid>2a2beb21-47a9-45c4-ba81-7b9cb898af78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'page.php']</value>
      <webElementGuid>18d87fa9-bc86-4792-883d-c6bbe02bae9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'page.php']</value>
      <webElementGuid>f54d9b46-2b4c-4cec-a8a8-1e625a50b7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'page.php' and (text() = '
			             Page
			          ' or . = '
			             Page
			          ')]</value>
      <webElementGuid>2cb8a399-5cbe-487b-a458-a8b64679c2c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
