<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders</name>
   <tag></tag>
   <elementGuidId>da9e4965-0cbf-43b4-a913-4fb2c0762bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'customer-order.php']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;customer-order\.php&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Orders&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1b0c98e-2f5c-4b4f-808e-57badfff9caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>customer-order.php</value>
      <webElementGuid>4344b2b7-f1a3-41fa-a968-f6294290b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orders</value>
      <webElementGuid>02cf4788-4d7d-46f3-a787-ebdf4cf9a61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b71b5b21975e75dd46144156d694c5b5</value>
      <webElementGuid>0ce2031d-cbe0-4af7-b42b-ceb190413869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'customer-order.php']</value>
      <webElementGuid>dc6d8f41-eefc-4b61-b04a-3c8af5d57ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'customer-order.php']</value>
      <webElementGuid>29714133-0507-4e59-b735-76df8f75d12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'customer-order.php' and (text() = 'Orders' or . = 'Orders')]</value>
      <webElementGuid>e75f7306-cae9-4f10-86c3-56df95a93a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
