<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Showing 1 to 1 of 1 entries (filtered f_979ba8</name>
   <tag></tag>
   <elementGuidId>7a0643bd-1319-4ae5-a880-c199e578d527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example1_info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#example1_info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Showing 1 to 1 of 1 entries (filtered from 2 total entries)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f7a9b85-8ffa-4f2d-a16e-30a46bc6d37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>04f31692-11e9-42dd-be00-bc184e11f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>example1_info</value>
      <webElementGuid>e8a82375-6c9a-4bee-a048-59d6a84f2c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>492652e8-1079-497e-97d2-002e425fd1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1e83948d-8dd7-47c2-8bb6-b3383cf07ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 1 of 1 entries (filtered from 2 total entries)</value>
      <webElementGuid>7594c4c7-b832-475a-b87e-7cbfbd79bdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1_info&quot;)</value>
      <webElementGuid>0fc23443-678f-471e-b2bc-c3103c0bb081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='example1_info']</value>
      <webElementGuid>37d53648-3527-444f-871b-4b98245691bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example1_wrapper']/div[3]/div/div</value>
      <webElementGuid>1a91207a-bf3a-4ecb-a8fb-2d11516d8881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[2]/following::div[3]</value>
      <webElementGuid>8e11e033-5316-4da1-abfa-a74544b7ecec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::div[3]</value>
      <webElementGuid>c9e6b299-d623-4230-99d1-9337d6058fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Confirmation'])[1]/preceding::div[3]</value>
      <webElementGuid>056c0a02-f2b7-4039-9a66-656c33e6f095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure want to delete this item?'])[1]/preceding::div[4]</value>
      <webElementGuid>bb8e6584-0706-4c27-8506-270e2da51d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 2 total entries)']/parent::*</value>
      <webElementGuid>1d8dd8ea-0d29-4848-97d3-10ec2ec1b095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>48b54acd-db61-40da-b46b-62a006f55d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'example1_info' and (text() = 'Showing 1 to 1 of 1 entries (filtered from 2 total entries)' or . = 'Showing 1 to 1 of 1 entries (filtered from 2 total entries)')]</value>
      <webElementGuid>6410dca9-0e57-48b0-886a-9ea4fcedfd51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
