<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Women</name>
   <tag></tag>
   <elementGuidId>5d38a9e7-f21c-4406-9494-24c47b30f694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.menu-dropdown-icon:nth-child(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' menu-dropdown-icon ') and (position() = 3)]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Women&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>234562b3-2bea-4411-a8f8-0e1f27ab3216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>product-category.php?id=2&amp;type=top-category</value>
      <webElementGuid>59876a69-9610-4e28-abe0-c673a6973e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>93e63db7-d5d0-4aa7-9250-4d34f6b177dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-01efeca220daa88aadb81751364f1014</value>
      <webElementGuid>3eb410b0-3720-407c-bea6-03fab8f7cc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' menu-dropdown-icon ') and (position() = 3)]/a</value>
      <webElementGuid>1d018965-dfdb-4b8c-9376-9fcbe375305c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' menu-dropdown-icon ') and (position() = 3)]/a</value>
      <webElementGuid>6795ba92-ac30-4040-8e72-8a86e234f3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'product-category.php?id=2&amp;type=top-category' and (text() = 'Women' or . = 'Women')]</value>
      <webElementGuid>5075b018-d941-4c5c-983d-2fd7ac5ded22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
